#-------------------------------- install_kafka.yml ------------------------------------
- name: install Confluent Kafka
  hosts: kafka #kafka broker server 대상
  tasks:
    - name: Add Kafka group
      ansible.builtin.group: #ansible이 가지고 있는 모듈중 group을 사용
        name: kafka # kafka group을 생성
        gid: 1001 # group ID
        system: false # 시스템 그룹은 false -> 일반그룹으로 생성
      become: yes # 수도권한으로 작업

    - name: Add Kafka user # user 모듈
      ansible.builtin.user:
        name: kafka # kafka user 생성
        shell: /bin/bash # login 셀은 /bin/bash 셀을 사용
        uid: 1001
        group: kafka
        groups: ubuntu # 추가적인 group은 ubuntu로 설정
        comment: User for Kafka Cluster
      become: yes

    - name: make directory
      ansible.builtin.file:
        path: /engine
        state: directory
      become: yes

    - name: unarchive file
      ansible.builtin.unarchive:
        src: /home/ec2-user/downloads/confluent-community-6.2.14.tar.gz
        dest: /engine
        copy: true
        owner: kafka
        group: kafka
      become: yes

    - name: make data directory
      ansible.builtin.file:
        path: /data
        state: directory
      become: yes

    - name: make data directory
      ansible.builtin.file:
        path: /src
        state: directory
      become: yes

    - name: create log directory
      become: yes
      file:
        path: /log
        owner: kafka
        group: kafka
        state: directory

    - name: make kafka segment directory
      ansible.builtin.file:
        path: /data/kafka-logs
        state: directory
        owner: kafka
        group: kafka
      become: yes

#-------------------------------- setting_hosts.yml ------------------------------------
- name: Setting /etc/hosts file
  hosts: kafka
  tasks:
    - name: setting kafka broker hosts
      blockinfile: # block의 내용을 한 번에 추가
        path: /etc/hosts
        block: | # 줄바꿈 기능
          172.31.27.133 kafka01
          172.31.32.153 kafka02
          172.31.48.244 kafka03
        marker: "# {mark} Setting datalake hosts"
      become: yes

    - name: setting hostname
      lineinfile: # 특정 내용을 찾아서 변경하는 모듈
        path: /etc/hostname
        regexp: '^(ip|kafka)'
        line: '{{ inventory_hostname }}' # kafka01 ~ kafka03
      become: yes

    - name: change timezone
      command: # command 모듈을 이용한 한국시간 설정
        cmd: timedatectl set-timezone Asia/Seoul
      become: yes

#-------------------------------- setting_hosts.yml ------------------------------------
- name: create python env # ansible playbook 이름
  hosts: kafka # kafka 서버들에서 실행
  tasks: # 아래에 있는 작업들을 순서대로 진행
    - name: install pkg for add repository #
      become: yes # 관리자 권한으로 시작
      apt:
        pkg: # 설치할 패키지
          - software-properties-common # 아래 저장소를 설치하기전 설치할 패키지
        update_cache: true

    - name: Add repo
      become: yes
      apt_repository:
        repo: ppa:deadsnakes/ppa # python 3.10을 설치하기위한 비공식 레파지토리 # 우분투 공식 레파지토리에는 python 3.10이 없음
        # sudo add-apt-repository ppa:deadsnakes/ppa

    - name: install python3.10, python3-pip, venv
      become: true
      apt:
        pkg:
          - python3.10
          - python3-pip
          - python3.10-venv
        update_cache: true

    - name: create python virtual environment # 가상환경 설치
      become: true
      command:
        cmd: python3.10 -m venv /src/kafka_venv
        creates: /src/kafka_venv

    - name: change owner to kafka
      become: true
      file:
        path: /src/kafka_venv
        owner: kafka
        group: kafka
        recurse: yes

    - name: Modify .bashrc #  가상환경 진입/ 환경변수에 경로하나 추가
      blockinfile:
        path: /home/kafka/.bashrc
        block: |
          source /src/kafka_venv/bin/activate  
          export PYTHONPATH="${PYTHONPATH}:/src/kafka-producer" 
          alias src="cd /src"
          alias bin="cd /engine/confluent-6.2.14/bin"
          alias logs="cd /engine/confluent-6.2.14/logs"
        marker: "# {mark} Setting bashrc"
      become: yes

#-------------------------------- setting_hosts.yml ------------------------------------

    - name: install Zookeeper
      hosts: kafka
      tasks:
        - name: Add Zookeeper group
          ansible.builtin.group: # zookeeper group 생성
            name: zookeeper
            gid: 1002 # group ID 1002로 설정
            system: false
          become: yes

    - name: Add Zookeeper user
      ansible.builtin.user: # zookeeper user 생성
        name: zookeeper
        shell: /bin/bash
        uid: 1002
        group: zookeeper
        comment: User for Zookeeper
      become: yes

    - name: make directory
      ansible.builtin.file:
        path: /engine
        state: directory
      become: yes

    - name: unarchive file
      ansible.builtin.unarchive: # 압축파일 풀기
        src: /home/ec2-user/downloads/apache-zookeeper-3.8.4-bin.tar.gz
        dest: /engine
        copy: true
        owner: zookeeper
        group: zookeeper
      become: yes

    - name: Install Java 17
      ansible:builtin.apt:
        name: openjdk-17-jre
        update_cache: true
      become: yes



